[package]
name = "pstime"
version = "0.1.0"
authors = ["Magnus Wallin <magnuswallin@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
